### ISSUE TITLE
Substitute bash color marker

### ISSUE THREAD

**Issue by rgarrigue** [emilast/vscode-logfile-highlighter#83] opened 2019-09-27 06:52 UTC
Hi

I've a log piped out from Molecule, Ansible's test framework. It looks like this

```
    TASK [ansible-role-base : Backup script] ***************************************
    [0;36mskipping: [molecule-common-debian10-systemd][0m
    [0;36mskipping: [molecule-common-debian9-systemd][0m
    [0;36mskipping: [molecule-common-ubuntu1804][0m
    
    PLAY RECAP *********************************************************************
    [0;33mmolecule-common-debian10-systemd[0m : [0;32mok=8   [0m [0;33mchanged=7   [0m unreachable=0    failed=0    [0;36mskipped=3   [0m rescued=0    ignored=0
    [0;33mmolecule-common-debian9-systemd[0m : [0;32mok=8   [0m [0;33mchanged=7   [0m unreachable=0    failed=0    [0;36mskipped=3   [0m rescued=0    ignored=0
    [0;33mmolecule-common-ubuntu1804[0m : [0;32mok=8   [0m [0;33mchanged=7   [0m unreachable=0    failed=0    [0;36mskipped=3   [0m rescued=0    ignored=0
    
--> [36mScenario: 'default'[0m
--> [36mAction: 'idempotence'[0m
[33mAn error occurred during the test sequence action: 'idempotence'. Cleaning up.[0m
--> [36mScenario: 'default'[0m
--> [36mAction: 'cleanup'[0m
[33mSkipping, cleanup playbook not configured.[0m
--> [36mScenario: 'default'[0m
--> [36mAction: 'destroy'[0m
```

Would it be possible to add a feature to substitute those with colors ? Not by default, with a switch "Enable shell color substitution" for example.

Best regards,

**Comment by emilast** [comment] 2020-07-15 12:40
Duplicate of #57.

No immediate plans to implement this, but I can see it would be useful.

**Closed by emilast** 2020-07-15 12:40 UTC
