### ISSUE TITLE
Highlighting does not work as expected

### ISSUE THREAD

**Issue by jankap** [emilast/vscode-logfile-highlighter#161] opened 2020-11-11 10:22 UTC
Hi, thanks for this extension. However, I'm having troubles:

![image](https://user-images.githubusercontent.com/12893844/98799890-fe085380-240f-11eb-839e-56b4fa3003fc.png)

There is no duration shown and the highlighting differs from your example. Do I have to configure something? I'm using Logfile highlighter v2.10.0 and VSCode November 2020.

Thank you very much!

**Comment by HaaLeo** [comment] 2020-11-12 12:05
Hi @jankap 

Using vscode v1.51.1 with logfilehighlighter v2.10.0 on macOS X I cannot reproduce this bug:
<img width="840" alt="image" src="https://user-images.githubusercontent.com/23164374/98937619-f23b9080-24e6-11eb-89a8-9d5ec258dca8.png">

Maybe some other extension is interfering with this one.
To check whether that is the case you can try to start vscode with `code --disable-extensions` and then only enable the logfilehighlighter.

Another possible cause for that could be your settings. Can you please share the entries of your `settings.json` file(s)?

**Comment by emilast** [comment] 2021-07-17 16:19
I'll close this now but feel free to report it again if there is still a problem.

**Closed by emilast** 2021-07-17 16:19 UTC
