### ISSUE TITLE
Add pattern for "Warning", "Info", "Error" for windows installation logs

### ISSUE THREAD

**Issue by weird-dreams** [emilast/vscode-logfile-highlighter#38] opened 2018-02-07 06:39 UTC
We often face logs of windows upgrades or migrations which all have those "keys" for their outputs:

```
2018-02-05 14:44:48, Warning               MIG    Could not create object Microsoft-Windows-Update-Ux-MusScnHandlers[@version="10.0.15063.850" and @arch="amd64" and @culture="neutral" and @context="perUser"]/settings. Exception class Mig::SideAwareWin32Exception: The request is not supported. [0x00000032] void __cdecl Mig::CStateDataStore::Create(class Mig::CDataUnit *)
2018-02-05 14:44:48, Info                  MIG    Error 50 during apply of object Microsoft-Windows-Update-Ux-MusScnHandlers[@version="10.0.15063.850" and @arch="amd64" and @culture="neutral" and @context="perUser"]/settings. Will ask shell application for resolution.
2018-02-05 14:44:48, Warning               SP     Error WRITE, 0x00000032 while gathering/applying object: State, Microsoft-Windows-Update-Ux-MusScnHandlers[@version="10.0.15063.850" and @arch="amd64" and @culture="neutral" and @context="perUser"]/settings. Will return 2
2018-02-05 14:44:48, Info                  MIG    Error 50 while applying object Microsoft-Windows-Update-Ux-MusScnHandlers[@version="10.0.15063.850" and @arch="amd64" and @culture="neutral" and @context="perUser"]/settings. Shell application requested ignore
2018-02-05 13:36:39, Error                 CONX   Windows::Compat::Appraiser::WicaApplicationInventory::AddItemProperty (546):   App Inventory returned duplicate file d:\users\aha\appdata\local\temp\~nsu.tmp\cu_.exe.[gle=0x8007000d]
2018-02-05 13:36:39, Error                 CONX   Windows::Compat::Appraiser::WicaApplicationInventory::AddItemProperty (546):   App Inventory returned duplicate file c:\program files (x86)\microsoft visual studio\2017\professional\common7\ide\devenv.exe.[gle=0x8007000d]

```
Could you please add this?
TIA, Andi

**Comment by HaaLeo** [comment] 2018-02-07 08:54
This is a possible duplicate of #37.

**Comment by emilast** [comment] 2018-02-07 22:18
Yes, possible duplicate (at least related) but we should try to only match these "keys" in the correct context, i.e. when they're used as log levels and not in natural language texts. In this case we could perhaps match on `, Error`  etc.

But I'm not sure, maybe it's worth it to always indicate Info, Debug, Warning, Error etc and accept that sometimes it will indicate them in other texts. There are so many variants that maybe it's better to be general.

**Comment by HaaLeo** [comment] 2018-02-08 07:41
It also maybe is possible to support custom log level programmatically using 
```typescript
vscode.window.activeTextEditor.setDecorations(decoration, ranges);
``` 
But it would take some to implement that properly (I currently only have limited time, too).

**Closed** 2018-02-08 20:30 UTC
